'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { AudioLines, ArrowRight, Loader2 } from 'lucide-react';
import { loginAction } from './actions';
import { Notice } from '@/components/studio/Primitives';
export default function LoginPage() {
  const [error, setError] = useState(''); const [pending, startTransition] = useTransition(); const router = useRouter();
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); startTransition(async () => { try { const result = await loginAction(form); if (result.success) { router.push('/'); router.refresh(); } else setError('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'); } catch { setError('เข้าสู่ระบบไม่ได้ กรุณาลองอีกครั้ง'); } }); }
  return <main className="login-page" id="main-content"><aside className="login-art"><div className="studio-brand"><AudioLines size={33} strokeWidth={1.4} /><span>SAX MUSIC<small>STUDIO</small></span></div><div><p className="eyebrow">THE SPACE BEHIND THE SOUND</p><h1>Your work.<br />Your sound.<br /><span>Your studio.</span></h1><div className="sound-lines" aria-hidden="true">{Array.from({ length: 32 }, (_, index) => <i key={index} />)}</div><p>พื้นที่จัดการผลงานของคุณ ตั้งแต่รูปปกและรายการเพลง ไปจนถึงการเผยแพร่ให้ผู้ฟัง</p></div><footer>SAX MUSIC / PORTFOLIO MANAGEMENT</footer></aside><div className="login-form-wrap"><form className="login-form form-stack" onSubmit={submit}><div><p className="eyebrow">WELCOME TO YOUR WORKSPACE</p><h2>เข้าสู่ Studio</h2><p className="muted">ใช้บัญชี admin ของคุณเพื่อจัดการผลงาน</p></div><label className="field-label" htmlFor="username">ชื่อผู้ใช้<input className="field" id="username" name="username" autoComplete="username" required disabled={pending} autoFocus /></label><label className="field-label" htmlFor="password">รหัสผ่าน<input className="field" id="password" name="password" type="password" autoComplete="current-password" required disabled={pending} /></label><Notice error>{error}</Notice><button className="btn btn-primary" type="submit" disabled={pending}>{pending ? <><Loader2 size={17} className="spin" />กำลังเข้าสู่ระบบ…</> : <>เข้าสู่ Studio <ArrowRight size={17} /></>}</button><footer>สำหรับผู้ดูแล Sax Music</footer></form></div></main>;
}
