'use client';
import { useCallback, useEffect, useState } from 'react';
import { Layers3, Plus, Pencil, Trash2 } from 'lucide-react';
import { adminFetch } from '@/lib/adminFetcher';
import { message, newId, type Category, type Project } from '@/lib/studio';
import { Dialog, Loading, Notice, OrderButtons } from './Primitives';
export default function Categories() {
  const [categories, setCategories] = useState<Category[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [form, setForm] = useState<{ id?: string; name: string } | null>(null);
  const load = useCallback(async (signal?: AbortSignal) => {
    try { const [c, p] = await Promise.all([adminFetch<Category[]>('/categories', { signal }), adminFetch<Project[]>('/projects', { signal })]); setCategories(c); setProjects(p); }
    catch (cause) { if (!signal?.aborted) setError(message(cause)); } finally { if (!signal?.aborted) setLoading(false); }
  }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  async function change(endpoint: string, method: string, body?: unknown) { setBusy(true); setError(''); try { await adminFetch(endpoint, { method, body: body === undefined ? undefined : JSON.stringify(body) }); await load(); setNotice('บันทึกหมวดหมู่แล้ว'); return true; } catch (cause) { setError(message(cause)); return false; } finally { setBusy(false); } }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!form) return; if (await change('/categories' + (form.id ? '/' + form.id : ''), form.id ? 'PUT' : 'POST', { id: form.id || newId(), name: form.name, display_order: Math.max(-1, ...categories.map(c => c.display_order)) + 1 })) setForm(null); }
  async function move(index: number, direction: number) { const list = [...categories]; [list[index], list[index + direction]] = [list[index + direction], list[index]]; await change('/categories/reorder', 'PATCH', { items: list.map((item, order) => ({ id: item.id, display_order: order })) }); }
  return <><div className="page-heading"><div><p className="eyebrow">ORGANIZE YOUR WORK</p><h1>หมวดหมู่<span className="title-dot">.</span></h1><p className="muted">จัดกลุ่มผลงานและลำดับที่แสดงบนหน้าเว็บ</p></div><button className="btn btn-primary" disabled={busy} onClick={() => { setError(''); setForm({ name: '' }); }}><Plus size={18} />เพิ่มหมวดหมู่</button></div><Notice error>{!form ? error : ''}</Notice><Notice>{notice}</Notice><div className="section-label"><span>{categories.length} หมวดหมู่</span><span>เปลี่ยนลำดับหรือการแสดงผลแล้วบันทึกทันที</span></div>{loading ? <Loading /> : <div className="category-list">{categories.map((category, index) => { const count = projects.filter(p => p.category_id === category.id).length; return <div className="category-row" key={category.id}><Layers3 size={23} className="muted" /><div className="category-info"><h2>{category.name}</h2><p>{count} โปรเจกต์ · {category.is_visible ? 'แสดงบนหน้าเว็บ' : 'ซ่อนทั้งหมวดจากหน้าเว็บ'}</p></div><div className="category-actions"><button className="switch-button" role="switch" aria-label={'แสดงหมวด ' + category.name + ' บนเว็บ'} aria-checked={Boolean(category.is_visible)} disabled={busy} onClick={() => void change('/categories/' + category.id, 'PUT', { is_visible: !category.is_visible })}>{category.is_visible ? 'แสดงบนเว็บ' : 'ซ่อนอยู่'}</button><button className="btn" disabled={busy} onClick={() => { setError(''); setForm({ id: category.id, name: category.name }); }}><Pencil size={15} />แก้ไข</button><OrderButtons name={category.name} first={index === 0} last={index === categories.length - 1} disabled={busy} move={direction => void move(index, direction)} /></div></div>; })}</div>}<Dialog open={Boolean(form)} title={form?.id ? 'แก้ไขหมวดหมู่' : 'เพิ่มหมวดหมู่'} busy={busy} onClose={() => { if (!busy) setForm(null); }}>{form && <form className="dialog-form" onSubmit={save}><label className="field-label">ชื่อหมวดหมู่<input className="field" autoFocus required maxLength={160} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} disabled={busy} /></label><Notice error>{error}</Notice><div className="form-actions">{form.id && <button type="button" className="btn btn-danger" disabled={busy || projects.some(p => p.category_id === form.id)} title="ย้ายโปรเจกต์ออกก่อนลบหมวดหมู่" onClick={async () => { if (window.confirm('ลบหมวดหมู่นี้?') && await change('/categories/' + form.id, 'DELETE')) setForm(null); }}><Trash2 size={15} />ลบหมวดหมู่</button>}<button type="button" className="btn" disabled={busy} onClick={() => setForm(null)}>ยกเลิก</button><button className="btn btn-primary" type="submit" disabled={busy || !form.name.trim()}>{busy ? 'กำลังบันทึก…' : 'บันทึกหมวดหมู่'}</button></div></form>}</Dialog></>;
}
